development:
  adapter: postgresql
  encoding: unicode
  database: proficiency-test_development
  host: localhost
  pool: 5
  username: frankystonlins
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: proficiency-test_test
  host: localhost
  pool: 5
  username: frankystonlins
  password: 